### ISSUE TITLE
p5/oF/Kivy are getting installed in /assets/presentation/

### ISSUE THREAD

**Issue by b3nson** [Tooloop/Tooloop-OS#26]
From my understanding/observing Processing, openFrameworks and Kivy are currently getting installed inside the `/assets/presentation/ `directory, which means they are deleted whenever i "install" a new app from within "App Center", right?!

Is it meant to be like that?

Wouldn't it be better to install/store those runtimes/libraries (p5/oF/Kivy) in a "global" place, usable for any app?

**Comment by vollstock** [comment]
Hm, I don’t know.
The whole install/uninstall process could need some thinking, though.

The process is now:

# Uninstall old app
1. Stop running presentation
2. Call provided uninstall script (if any)
3. Delete bundle files from settings server

# Install new app
1. Call provided install script (if any)
2. Copy bundle files to settings server
3. Copy provided data files (if any)
4. Delete old presentation
5. Copy new presentation

Notice, that the stuff in `/assets/data/` is _not_ deleted. This was for the exact same reason, you don’t want the framework to be deleted. This is so if the user has plenty of videos or images in the data folder. The coder provides an update of the app and asks the user to uninstall the old an install the new app. The data won't get lost.
Also the app doesn’t necessarily _own_ the files in data. The Kiosk Browser for instance, doesn’t know, whether theres a local website in data or not.

With frameworks that’s a little different. These boxes are no likely to change apps very often. If you deploy a machin in a museum or a trade fair, it will probably never chenge again. What I’m saying is, you testing things is not the intendet usecase for the machines.

From the top of my head, I can think of two solutions:

# 1. Give frameworks a place to live in

Right now there’s this hierarchy on the assets drive:

|           Path          |                                   Description                                   |
|-------------------------|---------------------------------------------------------------------------------|
| `/assets/presentation/` | your app                                                             |
| `/assets/data/`         | your images, videos                                            |
| `/assets/screenshots/`  | screenshots                                                |
| `/assets/logs/`         | log files                                    |
| `/assets/apps/`         | app bundles that are locally available to install through the settings server |

Maybe, we could add another folder `/assets/frameworks/`.

However, we will have to carefully think what this means for development workflows as e. g. openFrameworks relies on a relative path to the framework which you need to change in the make file of your app. (something I should document).

# 2. Don’t delete the presentation

Instead of brutally deleting the whole conetent in `/assets/presentation`, we could rely on the coder to add proper delete directives to the uninstall script. He would maybe know best, what to was installed.

**Comment by vollstock** [comment]
Relevant issue in Tooloop-Settings-Server: [#4 Concept for app center](https://github.com/vollstock/Tooloop-Settings-Server/issues/4)

**Comment by b3nson** [comment]
> you testing things is not the intendet usecase for the machines.

yes, that's a good point! :)

> openFrameworks relies on a relative path to the framework 

Would it change something, if you add the oF-runtime  (wherever it lives) to the linux-executable-`PATH` during oF-install?! Maybe not.

**Comment by b3nson** [comment]
At the moment the handling, respectively the expectations of how these framework-installations work, is **misleading** in my eyes.

The option/wording to INSTALL these frameworks, alongside with GPU-drivers etc, implies they persistently get installed on my system (to be used by apps).

So I consider it confusing, when they get deleted/uninstalled by ("only") changing the app.


Possible Solutions:
# 0. Frameworks are being installed on a per-app basis 
(kind of like now)
The install menu needs to say something like:
"Install Processing for currently active app"

But then it's still a little confusing, that i need to reinstall it every time I load/install the/a app.


# 1. Give frameworks a place to live in
"Install Processing" installs processing on the system (e.g. `/assets/bin/Processing-X.Y.Z`)

The install-option-stuff script could eventually also uninstall it again?!

An app now either calls the framework directly from where it lives, or
the framework gets symlinked into `/assets/presentation/bin/` .
Symlinked ...

1.  during the framework-installation 
2.  manually from within the install script of the app
3.  automatically from within the install script of the app because it is an explicitly defined requirement in app.json (?! not really)


# 2. Don’t delete the presentation / rely on the coder

Also an option worth thinking about...
but then the install-option should also be thought about again.

When the coder gets encouraged to handle the location/integration and removal of frameworks himself, he probably also wants to handle the installation or at least the install-location himself?!

So the install-option should maybe become a download-option...
like, we help you finding and downloading some frameworks fast and easy, but then the coder has to decide what to do with it, where and how to place, integrate and remove it again.



These are just my spontaneous thoughts... while not being very deep into the project!
😄 👊

**Comment by vollstock** [comment]
Hey @b3nson, I have thought about this some more and put up a design proposal that I wanted to do for a while now. Hava a look, I think you will like that ;-)

**App center proposal**
https://github.com/vollstock/Tooloop-Settings-Server/issues/4#issuecomment-418665340

The proposal takes this from the above discussion:

- Frameworks are installable bundles
- Presentation can depend on other bundles and when they do, those are installed automatically
- Bundles will never be uninstalled automatically

I am totally not clear, what that all means for implementations details but I guess, it’s a good idea to align our visions. :-) Also I still don’t know whether all that should already go into beta or will have to wait for 1.0.

Anyway, knowing, that (something like) this is where we’re heading makes me forgive some shitty shortcomings of the optionals installer script which simply will have to do until we get a propoer app center.

**Comment by vollstock** [comment]
I am closing this as I have dropped Processing and openframeworks installers  in current development…
